title: Sandbox3-pages
description: Sandbox for learning and testing Jeklyll
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
